name: Build
on: 
   push:
     branches:
       - 'test/performance'

jobs:
  build:
      name: build
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2

        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v2
            
        - name: Build
          run: |
            export DOCKER_BUILDKIT=1
            docker buildx build --platform=linux/arm64 -t gihub-runner-lab .